#include "parser.c"
int main(int argc, char* argv[])
{
	removeComments(argv[1],argv[2]);
	// HEAD* tokenList = getAllTokens(argv[2]);
	HEAD* tokenList = initializeLinkedList();
	FILE* g_file = fopen("grammar.txt","r");
	Grammar* g = extractGrammarFromFile(g_file);
	ComputeFirstSets(g);
	ComputeFollowSets(g);
	parsingTable pTable = createParsingTable(g);
	ParseTree ptree = NULL;
	// printGrammar(g);
	// printGrammarRulesReverse(g);
	// printRHSOccurrences(g);
	// printFirstSets(g);
	// printFollowSets(g);
	// printParsingTable(pTable);
	while(1)
	{
		printf("Choose an option\n");
		printf("1. Print comment free code\n");
		printf("2. Print the token list generated by lexer\n");
		printf("3. Parse to verify syntactic correctness of code\n");
		printf("4. Print the parse tree to file\n");
		printf("5. Exit\n");
		printf("Option:");
		int c;
		scanf("%d",&c);
		if(c == 1)
		{
			printCommentFreeCode(argv[2]);
		}
		else if(c == 2)
		{
			if(tokenList->first == NULL)
			{
				printf("First run parser then only tokens will be generated by lexer.\n");
			}
			else
			{
				printTokens(tokenList);
			}
		}
		else if(c == 3)
		{
			ptree = parseInput(g,argv[2],tokenList,pTable);
		}
		else if(c == 4)
		{
			if(ptree == NULL)
			{
				printf("First parse input code to verify syntactic correctness of code.\n");
			}
			else
			{
				printParseTree(ptree,argv[3]);
			}
		}
		else
		{
			return 0;
		}
	}
	return 0;
}