// ID: 2015A7PS0355P
// Name: Vignesh N
#include "codeGenerator.c"
int main(int argc, char* argv[])
{
	if(argc != 3)
	{
		printf("usage: ./stage1exe testcase.txt parsetreeoutfile.txt\n");
		return 0;
	}
	HEAD* tokenList = initializeLinkedList();
	FILE* g_file = fopen("grammar.txt","r");
	if(g_file == NULL)
	{
		printf("Grammar file not opened successfully\n");
		return 0;
	}
	Grammar* g = extractGrammarFromFile(g_file);
	// printGrammar(g);
	ComputeFirstSets(g);
	ComputeFollowSets(g);
	parsingTable pTable = createParsingTable(g);
	ParseTree ptree = NULL;
	ASTNode* asTree = NULL;
	errorHead* symTableErrorListHead = initializeErrorHead();
	errorHead* typeCheckingErrorsHead = initializeErrorHead();
	SymbolTable* symTable = NULL;
	// printGrammar(g);
	// printGrammarRulesReverse(g);
	// printRHSOccurrences(g);
	// printFirstSets(g);
	// printFollowSets(g);
	// printParsingTable(pTable);
	while(1)
	{
		printf("Choose an option\n");
		printf("1. Print comment free code\n");
		printf("2. Print the token list generated by lexer\n");
		printf("3. Parse to verify syntactic correctness of code\n");
		printf("4. Print the parse tree to file\n");
		printf("5. Create AST\n");
		printf("6. Print AST\n");
		printf("7. Create Symbol table and do type checking\n");
		printf("8. Print ST, semantic erors\n");
		printf("9. Generate IntCode and print it\n");
		printf("10. Generate code.\n");
		printf("11. Exit\n");
		printf("Option:");
		int c;
		scanf("%d",&c);
		if(c == 1)
		{
			removeComments(argv[1]);
		}
		else if(c == 2)
		{
			if(tokenList->first == NULL)
			{
				printf("First run parser then only tokens will be generated by lexer.\n");
			}
			else
			{
				printTokens(tokenList);
			}
		}
		else if(c == 3)
		{
			ptree = parseInput(g,argv[1],tokenList,pTable);
			if(ptree == NULL)
			{
				printf("file not opened successfully\n");
			}
		}
		else if(c == 4)
		{
			if(ptree == NULL)
			{
				printf("First parse input code to verify syntactic correctness of code.\n");
			}
			else
			{
				printParseTree(ptree,argv[2]);
			}
		}
		else if(c == 5)
		{
			if(ptree == NULL)
			{
				printf("First parse input code to verify syntactic correctness of code.\n");
			}
			else
			{
				asTree = createASTFromParseTree(ptree);
			}
		}
		else if(c == 6)
		{
			if(asTree == NULL)
			{
				printf("First create AST.\n");
			}
			else
			{
				printAST(asTree);
			}
		}
		else if(c == 7)
		{
			symTable = createSymbolTable(asTree,symTableErrorListHead);
			doTypeChecking(asTree, symTable,typeCheckingErrorsHead);
		}
		else if(c == 8)
		{
			printSymbolTable(symTable);
			printErrors(symTableErrorListHead,typeCheckingErrorsHead);
		}
		else if(c == 9)
		{
			int* tempVarNum = (int*)malloc(sizeof(int));
			int* labelVarNum = (int*)malloc(sizeof(int));
			*tempVarNum = 0;
			*labelVarNum = 0;
			createIntermediateCode(asTree,symTable,tempVarNum,labelVarNum);
			appendAllStatements(asTree);
			printIntCode(asTree->code);
			printSymbolTable(symTable);
		}
		else if(c == 10)
		{
			FILE* codeFile = fopen("code.asm","w");
			generateCode((codeNode*)asTree->code,symTable,codeFile);
			fclose(codeFile);
		}
		else
		{
			break;
		}
	}
	free(g);
	free(pTable);
	// free(ptree);
	fclose(g_file);
	return 0;
}